name: waterfall
recipe: drupal9
config:
  framework: drupal9
  site: waterfall
  edge: false
  webroot: web
  php: 8.2
  config:
    database: mysql
services:
  defaults:
    type: node:14
  appserver:
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - npm install --global gulp
    run_as_root:
      - "a2enmod headers && service apache2 reload"
      - "cd $LANDO_MOUNT && cd web/themes/custom/waterfall && npm install -g grunt-cli gulp-cli bower -y"
    run:
      - "cd $LANDO_MOUNT && cd web/themes/custom/waterfall && npm install && grunt --timer --quiet --no-validate"
  database:
    type: mysql:8.0
  php:
    type: php:8.2
  node:
    type: node:14
    build:
      - npm install
      - gulp
    globals:
      gulp-cli: 2.3.0
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  phpmyadmin:
    - phpmyadmin.waterfall-dev.lndo.site
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
